name: Unittests

on: [push]

jobs:
  unittest-with-pytest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest
    - name: Get code coverage
      run: |
        conda install pytest-cov
        $CONDA/bin/pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-AoC2020
        fail_ci_if_error: true
        path_to_write_report: ./codecov_report.txt
        verbose: true
